/**
 * Proves the indexes matter: runs 3 real queries with EXPLAIN ANALYZE, drops the
 * indexes they use, runs them again, then recreates the indexes.
 * Writes the timings to docs/PERFORMANCE.md.
 *
 *   SEED_ASSET_COUNT=100000 SEED_RESET=true npx prisma db seed
 *   npx tsx scripts/explain.ts
 */
import fs from "node:fs";
import path from "node:path";
import { PrismaClient } from "@prisma/client";

try {
  process.loadEnvFile();
} catch {
  // env from shell
}
const prisma = new PrismaClient();

const QUERIES = [
  {
    name: "Filter by stage + type, page 1",
    sql: `SELECT id, "assetCode", name FROM "Asset"
          WHERE status = 'UNDER_MAINTENANCE' AND "typeId" = (SELECT id FROM "AssetType" WHERE "codePrefix" = 'WP')
          ORDER BY "updatedAt" DESC LIMIT 20`,
    indexes: ["Asset_status_idx", "Asset_typeId_idx", "Asset_updatedAt_idx"],
  },
  {
    name: "Overdue maintenance",
    sql: `SELECT id, "assetCode", "nextMaintenanceDate" FROM "Asset"
          WHERE "nextMaintenanceDate" < now() - interval '30 days'
          ORDER BY "nextMaintenanceDate" LIMIT 20`,
    indexes: ["Asset_nextMaintenanceDate_idx"],
  },
  {
    name: "Search custom field (JSONB)",
    sql: `SELECT count(*) FROM "Asset" WHERE attributes @> '{"lamp_type":"CFL"}'`,
    indexes: ["asset_attributes_gin"],
  },
];

type Plan = { ms: number; node: string };

async function explain(sql: string): Promise<Plan> {
  // Warm the cache once so both runs are compared fairly, then measure.
  await prisma.$queryRawUnsafe(sql);
  const rows = await prisma.$queryRawUnsafe<{ "QUERY PLAN": unknown }[]>(`EXPLAIN (ANALYZE, FORMAT JSON) ${sql}`);
  const plan = (rows[0]["QUERY PLAN"] as { "Execution Time": number; Plan: Record<string, unknown> }[])[0];
  // Name of the deepest scan node (Seq Scan / Index Scan / Bitmap Index Scan).
  const scans: string[] = [];
  const walk = (n: Record<string, unknown>) => {
    if (String(n["Node Type"]).includes("Scan")) scans.push(`${n["Node Type"]}${n["Index Name"] ? ` (${n["Index Name"]})` : ""}`);
    ((n.Plans as Record<string, unknown>[]) ?? []).forEach(walk);
  };
  walk(plan.Plan);
  return { ms: plan["Execution Time"], node: scans.filter((s) => !s.includes("AssetType")).join(", ") };
}

async function main() {
  const count = await prisma.asset.count();
  const defs = await prisma.$queryRawUnsafe<{ indexname: string; indexdef: string }[]>(
    `SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'Asset'`,
  );
  const defOf = (name: string) => defs.find((d) => d.indexname === name)!.indexdef;

  const rows: string[] = [];
  for (const q of QUERIES) {
    const withIdx = await explain(q.sql);
    const saved = q.indexes.map(defOf);
    for (const name of q.indexes) await prisma.$executeRawUnsafe(`DROP INDEX "${name}"`);
    await prisma.$executeRawUnsafe(`ANALYZE "Asset"`);
    const without = await explain(q.sql);
    for (const def of saved) await prisma.$executeRawUnsafe(def);
    await prisma.$executeRawUnsafe(`ANALYZE "Asset"`);
    const speedup = without.ms / withIdx.ms;
    rows.push(`| ${q.name} | ${without.ms.toFixed(1)} ms · ${without.node} | ${withIdx.ms.toFixed(2)} ms · ${withIdx.node} | ${speedup.toFixed(0)}× |`);
    console.log(`${q.name}: ${without.ms.toFixed(1)} ms -> ${withIdx.ms.toFixed(2)} ms`);
  }

  const md = `# PERFORMANCE.md — indexes on ${count.toLocaleString("en-IN")} assets

Generated by \`api/scripts/explain.ts\` on ${new Date().toISOString().slice(0, 10)} (local Docker Postgres 16, laptop).
Each query is run once to warm the cache, then measured with \`EXPLAIN (ANALYZE)\`. The script then drops the index(es) the query uses, measures again, and recreates them.

| Query | Without index | With index | Faster |
|---|---|---|---|
${rows.join("\n")}

## The queries

${QUERIES.map((q) => `**${q.name}** (indexes: ${q.indexes.map((i) => `\`${i}\``).join(", ")})\n\`\`\`sql\n${q.sql.replace(/\n\s+/g, "\n")}\n\`\`\``).join("\n\n")}

## How to read EXPLAIN output

- **Seq Scan**: Postgres reads every row of the table and checks each one. Cost grows with the table: 10× more assets, ~10× slower.
- **Index Scan**: Postgres walks a B-tree index straight to the matching rows (like a book's index), then reads only those rows. With \`ORDER BY ... LIMIT 20\` it can stop after 20 rows.
- **Bitmap Index Scan → Bitmap Heap Scan**: Postgres first collects the locations of all matching rows from the index, then reads those table pages in physical order. Used when many rows match, and for the GIN index on JSONB (\`attributes @> '{...}'\`).
- **Execution Time** is what the database actually spent; planning time is small and not shown.

To reproduce:
\`\`\`bash
cd api
SEED_ASSET_COUNT=100000 SEED_RESET=true npx prisma db seed
npx tsx scripts/explain.ts
\`\`\`
`;
  fs.writeFileSync(path.resolve(__dirname, "../../docs/PERFORMANCE.md"), md);
  console.log("Wrote docs/PERFORMANCE.md");
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
